[package]
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
name = "nrf-softdevice-examples"
version = "0.1.0"

[features]
default = [
    "ble-l2cap",
    "ble-gatt-server",
    "ble-gatt-client",
]

ble-l2cap = ["nrf-softdevice/ble-l2cap"]
ble-gatt-server = ["nrf-softdevice/ble-gatt-server"]
ble-gatt-client = ["nrf-softdevice/ble-gatt-client"]

[dependencies]
embassy = { version = "0.1.0"}
embassy-nrf = { version = "0.1.0", features = [ "52840" ]}
cortex-m        = { version = "0.6.4" }
cortex-m-rt = "0.6.13"
cortex-m-rtic = { version = "0.5.5", optional = true }
panic-probe = "0.1.0"
nrf52840-hal    = { version = "0.11.0" }
nrf-softdevice = { version = "0.1.0", path = "../nrf-softdevice", features = [ "nrf52840", "s140", "ble-peripheral", "ble-central"] }
nrf-softdevice-s140 = { version = "0.1.1", path = "../nrf-softdevice-s140" }
futures = { version = "0.3.5", default-features = false }
fixed = "1.2.0"
heapless = "0.5.6"
alloc-cortex-m = "0.4.0"


[[bin]]
name = "rtic"
required-features = ["cortex-m-rtic"]

[[bin]]
name = "ble_bas_peripheral"
required-features = ["ble-gatt-server"]

[[bin]]
name = "ble_bas_central"
required-features = ["ble-gatt-client"]

[[bin]]
name = "ble_peripheral_onoff"
required-features = ["ble-gatt-server"]

[[bin]]
name = "flash"
required-features = []

[[bin]]
name = "interrupts"
required-features = []
